development:
  adapter: postgresql
  encoding: unicode
  database: ror_app_development
  pool: 5
  username: oleg

test:
  adapter: postgresql
  encoding: unicode
  database: ror_app_test
  pool: 5
  username: oleg
  password:
